Block 4 y 5 Fix decimal & Radom Tasks
mgutierrezc/time_others pull request #3
Opened 2022-03-02 22:38 UTC by Sergio2405

2022-03-02 22:48 UTC, Sergio2405 commented
@mgutierrezc esta listo para pull. Decimal places fixed y funcion Randomized45 que randomiza el nro de tareas para el bloque 4 y 5

2022-03-04 13:59 UTC, mgutierrezc requested changes
Todavía estás añadiendo archivos de __temp_static_root/. No debemos tener nada temporal en el repo. Añadir exepción en `.gitignore` y borrar archivos

Si en el gitginore no hay regla para los otros temporales como pycache, añadir también

2022-03-04 16:27 UTC, Sergio2405 commented
@mgutierrezc marcooo cree el gitignore y puse __temp_migrations y __temp_static_root y sale conflictossss

2022-03-07 03:49 UTC, mgutierrezc commented
@Sergio2405 revisaré este pull ahora y te indicaré siguientes pasos

2022-03-07 03:54 UTC, mgutierrezc commented
@Sergio2405 lo veo bien. Hagamos lo sgte. 

- Muevete al master y elimina todas las carpetas de temporales que eliminaste en tu branch.
- Pushea al master esos cambios en un unico commit
- Si a pesar de eso hay conflictos en este PR, sigue las sgtes instrucciones

![image](https://user-images.githubusercontent.com/43623521/156965075-774798fc-afdf-4527-9bde-17594fd51ef8.png)

2022-03-07 07:17 UTC, Sergio2405 commented
@mgutierrezc ya marco, ahora si se puede hacer merge

2022-03-07 15:31 UTC, mgutierrezc approved these changes

2022-03-07 15:31 UTC, merged